# yaml形式でgithub-actionの記述
# yaml のインデントは基本スペース: 2

name: frontend

# ワークフロー（ジョブ）が実行される条件
# masterブランチのpushイベントの際にワークフローのジョブが実行される
on:
  push: 
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/**'

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write
  contents: read

jobs:
  # デプロイジョブ
  deploy:
    # job実行ランナー
    runs-on: ubuntu-latest
    steps:
      # pushしたgitの内容をチェックアウト
      - uses: actions/checkout@v3
      # OpenID Connect を使用した認証
      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/github-action-frontend-role
          aws-region: ap-northeast-1
      # サービス状態
      - run: aws s3 sync . s3://${BACKET_NAME} --exact-timestamps --region ap-northeast-1
        env:
          BACKET_NAME: ${{secrets.FRONTEND_BACKET_NAME}}
      # echo アクション
      - uses: ./.github/actions/echo_action
